---
actions:
  to: kubernetes/service.yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{artifactId}}
  name: {{artifactId}}-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{artifactId}}
  sessionAffinity: None
  type: ClusterIP
