---
actions:
  to: skaffold.yaml
---
apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: {{artifactId}}
build:
  artifacts:
  - image: {{artifactId}}
    custom:
      buildCommand: ./mvnw spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=$IMAGE
      dependencies:
        paths:
          - src
          - pom.xml
deploy:
  kubectl:
    manifests:
    - kubernetes/deployment.yaml
    - kubernetes/service.yaml
portForward:
  - resourceType: service
    resourceName: {{artifactId}}-service
    port: 80
    localPort: 8080
